### ISSUE TITLE
[info] Tools that can help you

### ISSUE THREAD

**Issue by cyrinux** [koutto/jok3r#12]
Hi @koutto,

I want to share with you a cool tool which can maybe help you to monitor the stuff you put in this project, in case you don't know it:  https://github.com/thp/urlwatch
Sorry for the noise if this not interest you.

**Comment by koutto** [comment]
Thanks.
Here are some resources I use for monitoring new hacking tools that might be useful to add in here:
- https://www.kitploit.com/
- https://www.reddit.com/r/netsec/
- and of course Twitter
