### ISSUE TITLE
[enhancement] Importing multiple nmap xml files

### ISSUE THREAD

**Issue by emcthbe** [koutto/jok3r#17]
It would be useful to be able to import nmap xml files from a directory for instance

**Comment by cyrinux** [comment]
This should do the job, you can use wildcard like `~/nmap/*/*.xml`

https://github.com/koutto/jok3r/pull/19

**Comment by koutto** [comment]
I have tested this new feature and it works well ! Thanks @cyrinux 
I am closing the issue

**Comment by cyrinux** [comment]
Cool, glad to help :)

**Comment by emcthbe** [comment]
I have rebased from master and get it to work too. Thanks for the quick turn around
