### ISSUE TITLE
Wappalyzer error

### ISSUE THREAD

**Issue by Mjunior1** [koutto/jok3r#2]
I am trying to run the command below, but the Wappalyzer error and the scan appear.

`python3 jok3r.py attack -t https://www.site-test.com.br/ --add SITE-TEST`

And result:

`[?] Start attack ? [Y/n] Y

[*] HTTP Response headers:
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/8.5
Set-Cookie: ASP.NET_SessionId=nt0g54aegvmtpkrdwbbcl1c; path=/; HttpOnly
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Mon, 04 Feb 2019 23:43:19 GMT
Content-Length: 14784

[*] [SMART] Running initialization method...
[*] HTTPS protocol detected from URL
[*] Server detected from banner: iis
**[!] Wappalyzer error: 'ascii' codec can't decode byte 0xc2 in position 86207: ordinal not in range(128)`**

**Comment by koutto** [comment]
Thanks for the feedback. Should be fixed in new version that has just been pushed (v3.0)
