### ISSUE TITLE
[bug] db is not recognized command, alias or macro

### ISSUE THREAD

**Issue by cyrinux** [koutto/jok3r#22]
At jok3r.py db start i got this:

![image](https://user-images.githubusercontent.com/519083/61184959-b32bcf80-a653-11e9-83b1-2d22dd9ed7c2.png)

**Comment by cyrinux** [comment]
The culprit https://github.com/koutto/jok3r/blob/d4ce9646ee6e6e333963e3f572107dcea04938c8/lib/core/ArgumentsParser.py#L238
In fact it's because all the help/subcommand part of db is not yet done.

**Comment by koutto** [comment]
Strange, I don't have this problem here, running in th Docker container :

![jok3r_db](https://user-images.githubusercontent.com/26327909/61188400-a96b9180-a67e-11e9-9e69-adf3ea48e593.png)

Are you sure it is not due to the work you've done on the branch add-shodan ?

**Comment by cyrinux** [comment]
Hmmmmm good point, now I'm not sure. :) I search!

**Comment by cyrinux** [comment]
After removing all shodan related code i get yet the problem, but i confirm that the current docker image don't get the problem. Hmm

**Comment by cyrinux** [comment]
Wow seems it's a library version/missing problem, or something like this. Trying my code in the container works well.

**Comment by cyrinux** [comment]
I can't find which lib do this behavior. I close this to not pollute.
