### ISSUE TITLE
Unable to scan and install delete directorys

### ISSUE THREAD

**Issue by S0me1-dev** [koutto/jok3r#42]
.

**Comment by hastalamuerte** [comment]
bin/bash: /usr/local/rvm/scripts/rvm: No such file or directory
/bin/bash: rvm: command not found
/bin/bash: rvm: command not found

but then it starts to work....

**Comment by hastalamuerte** [comment]
plz help.. maybe i should reinstall all? dont want to use docker..

**Comment by hastalamuerte** [comment]
https://prnt.sc/s8aetf its just stopped(
