### ISSUE TITLE
Docker pull error

### ISSUE THREAD

**Issue by rationalthinker1** [koutto/jok3r#5]
Hello,
When I use the command, `docker pull koutto/jok3r`, I get the error below:
`Error response from daemon: manifest for koutto/jok3r:latest not found`

**Comment by koutto** [comment]
Hello,
Sorry for this. It was because I was still working on pushing the new Docker image and the tag I used was not "latest".
Anyway, everything should work now (just tested it) : 
sudo docker pull koutto/jok3r
