### ISSUE TITLE
Error when importing nmap xml file to db

### ISSUE THREAD

**Issue by grantwadlington** [koutto/jok3r#9]
OS:  Kali Linux
Ran the jok3r update script on 7-10-19. All tools updated successfully.

After creating a new mission, I attempted to import the saved nmap xml file as I have done in the past and receive the following error:

```
jok3rdb[netgear]> nmap '/root/jok3r/netgear.xml' 

[*] Importing Nmap results from /root/jok3r/netgear.xml
[*] Each service will be re-checked to detect HTTP services. Use --no-http-recheck if you want to disable it (faster import)

EXCEPTION of type 'IndexError' occurred with message: 'list index out of range'
To enable full traceback, run the following command:  'set debug true'
```

**Comment by koutto** [comment]
Hey,
Are you running in the Docker container or you installed it on your box ?
Can you type "set debug true", and re-do the import, and then paste here the stacktrace displayed ?

I have an idea of the problem, but need the stacktrace, thanks !

**Comment by cyrinux** [comment]
@grantwadlington which params have you use for your scan?
I just try and i can well import which db command nmap myscan.xml a xml from  `nmap -sV -oX myscan ip` for example.

**Comment by grantwadlington** [comment]
@koutto I didn't use Docker, just manually installed. I've used it in the past with no issue. I'll try running grabbing the debug.

@cyrinux  I've tried  "nmap -T4 -A -v  X.X.X.X/24"  &  "nmap -sV -T4 -O -F --version-light"  both return the error.

**Comment by cyrinux** [comment]
@grantwadlington always on a network? What about a single ip? Which version of nmap do you use?
I make try from my side, will tell you.

**Comment by koutto** [comment]
@grantwadlington Yes, looking forward your debug trace, will be very useful to see where the problem comes from ! Thanks

**Comment by cyrinux** [comment]
@grantwadlington i just tried with my home network, so several devices/services and your second command line, appending `-oX /tmp/try.xml`, then in a fresh `mission`, i `nmap /tmp/try.xml` and it works like a charm.

**Comment by grantwadlington** [comment]
Not sure if there was an update that fixed the issue but I tried a new scan using the same nmap parameters and was succesfully able to import the nmap.xml into the mission, as before. So, issue resolved. Thanks for all the responses.
